name: "Cargo update"

on:
  workflow_dispatch:
  schedule:
    # At 7:00am on Wednesday
    - cron: "0 7 * * 3"

jobs:
  flake_update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install nix
        uses: cachix/install-nix-action@v31
        with:
          install_url: https://releases.nixos.org/nix/nix-2.32.4/install

      - name: Flake update
        run: nix develop .#ci --command cargo update

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.HRA2_GITHUB_TOKEN }}
          commit-message: "chore: update Cargo.lock file"
          title: "chore: update Cargo.lock file"
          body: "This PR updates the Cargo.lock file."
          branch: "update-cargo-lock"
          base: "main"
          team-reviewers: holochain/holochain-devs
